import "./globals.css";
import 'leaflet/dist/leaflet.css'
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import BackToTop from "@/components/BackToTop";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" dir="ltr"  data-scroll-behavior='smooth'>
			<body className="font-poppins antialiased">
				<div className="flex flex-col min-h-screen">
					<Header />
					<main className="flex-1">{children}</main>
					<Footer />
					<BackToTop />
				</div>
			</body>
		</html>
	);
}