export const languages = [
	{ code: "en", label: "English", flag: "🇺🇸", dir: "ltr" },
	{ code: "ar", label: "Arabic", flag: "🇸🇦", dir: "rtl" },
	{ code: "fr", label: "French", flag: "🇫🇷", dir: "ltr" },
	{ code: "ru", label: "Russian", flag: "🇷🇺", dir: "ltr" },
	{ code: "es", label: "Spanish", flag: "🇪🇸", dir: "ltr" },
];

export const countries = [
	"Afghanistan",
	"Albania",
	"Algeria",
	"Andorra",
	"Angola",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahrain",
	"Bangladesh",
	"Belarus",
	"Belgium",
	"Belize",
	"Bhutan",
	"Bolivia",
	"Bosnia and Herzegovina",
	"Botswana",
	"Brazil",
	"Brunei",
	"Bulgaria",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Chile",
	"China",
	"Colombia",
	"Costa Rica",
	"Croatia",
	"Cuba",
	"Cyprus",
	"Czech Republic",
	"Denmark",
	"Dominican Republic",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Estonia",
	"Ethiopia",
	"Finland",
	"France",
	"Georgia",
	"Germany",
	"Ghana",
	"Greece",
	"Guatemala",
	"Honduras",
	"Hong Kong",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran",
	"Iraq",
	"Ireland",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kuwait",
	"Kyrgyzstan",
	"Laos",
	"Latvia",
	"Lebanon",
	"Libya",
	"Lithuania",
	"Luxembourg",
	"Malaysia",
	"Maldives",
	"Mexico",
	"Moldova",
	"Monaco",
	"Mongolia",
	"Morocco",
	"Myanmar",
	"Nepal",
	"Netherlands",
	"New Zealand",
	"Nigeria",
	"North Korea",
	"Norway",
	"Oman",
	"Pakistan",
	"Panama",
	"Paraguay",
	"Peru",
	"Philippines",
	"Poland",
	"Portugal",
	"Qatar",
	"Romania",
	"Russia",
	"Saudi Arabia",
	"Serbia",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"South Africa",
	"South Korea",
	"Spain",
	"Sri Lanka",
	"Sweden",
	"Switzerland",
	"Syria",
	"Taiwan",
	"Tajikistan",
	"Thailand",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom",
	"United States",
	"Uruguay",
	"Uzbekistan",
	"Venezuela",
	"Vietnam",
	"Yemen",
	"Zambia",
	"Zimbabwe",
];
